#!/bin/bash

for i in "$@"
do
case $i in
    --name=*)
    NAME="${i#*=}"
    ;;
    --image=*)
    IMAGE="${i#*=}"
    ;;
    --extra-args=*)
    ARGS="${i#*=}"
    ;;
esac
done

echo "Starting container" ${NAME} "from image" ${IMAGE} "with additional args " ${ARGS}

docker rm -f $NAME

CONTAINER_ID=$(docker run -d --name ${NAME} ${ARGS} -it ${IMAGE}) 

echo "Got container "$CONTAINER_ID

IP=$(docker inspect --format '{{.NetworkSettings.IPAddress}}' ${NAME})

echo "Container IP address "$IP

sed -i "/$NAME/d" /etc/hosts

echo "$IP $NAME" >> /etc/hosts

#sshpass -f password.txt ssh-copy-id -i ~/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ndphu@${NAME}
sshpass -f password.txt ssh-copy-id -i ~/.ssh/id_rsa.pub ndphu@${NAME}

