#!/bin/bash

IMAGE=$1
NAME=$2

CONTAINER_ID=$(docker run -d --name $NAME -it $IMAGE) 

IP=$(docker inspect --format '{{.NetworkSettings.IPAddress}}' $NAME)

echo "$IP $NAME" >> /etc/hosts
echo "$IP" >> known_hosts

sshpass -f password.txt ssh-copy-id -i ~/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ndphu@$NAME


